version: '3.4'

services:

  blazorapp:
    image: ${DOCKER_REGISTRY-}blazorappnginx
    build:
      context: .
      dockerfile: BlazorAppNginx/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SignalR__BaseUrl=http://localhost
      - Redis__ConnectionString=redis:6380
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - protected_keys:/root/.aspnet/DataProtection-Keys

  bapp-nginx:
    container_name: nginx-bapp-test
    image: nginxplus
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blazorapp
    ports:
      - "4002:80"

volumes:
  # Storing keys here is just for the PoC not recommended for PROD. 
  # see: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0
  protected_keys: